### ISSUE TITLE
OS support

### ISSUE THREAD

**Issue by simlw** [electron-userland/electron-installer-dmg#20]
Does this package can only be run on OSX ? When I package on Linux, I get the following error:
`
/home/xxxx/jenkins/workspace/Recorder-Build-test/gulpfile.js:35
    if (err) throw err;
             ^

Error: Must be run on OSX
    at module.exports (/home/xxxx/jenkins/workspace/Recorder-Build-test/node_modules/electron-installer-dmg/index.js:52:17)
    at packageDmg (/home/xxxx/jenkins/workspace/Recorder-Build-test/gulpfile.js:28:3)
    at /home/xxxx/jenkins/workspace/Recorder-Build-test/gulpfile.js:186:5
    at /home/xxxx/jenkins/workspace/Recorder-Build-test/node_modules/electron-packager/index.js:266:7
    at end (/home/xxxx/jenkins/workspace/Recorder-Build-test/node_modules/run-series/index.js:8:15)
    at done (/home/xxxx/jenkins/workspace/Recorder-Build-test/node_modules/run-series/index.js:11:10)
    at each (/home/xxxx/jenkins/workspace/Recorder-Build-test/node_modules/run-series/index.js:16:43)
    at /home/xxxx/jenkins/workspace/Recorder-Build-test/node_modules/electron-packager/common.js:291:7
    at next (/home/xxxx/jenkins/workspace/Recorder-Build-test/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/home/xxxx/jenkins/workspace/Recorder-Build-test/node_modules/rimraf/rimraf.js:110:9)
`

**Comment by francisco-sanchez-molina** [comment]
Linux support is very useful for using a ci environment 

Thanks!

**Comment by mebibou** [comment]
This should be closed as it is already in the underlying [appdmg library](https://github.com/LinusU/node-appdmg/issues/14)

**Comment by MarshallOfSound** [comment]
As @mebibou mentioned this should be tracked upstream at https://github.com/LinusU/node-appdmg/issues/14
